# Site settings
title: Hi, I'm Can
description: Can Sözbir's professional portfolio site
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Can Sözbir
user_description: I am a junior software developer who is extremely motivated to constantly develop his skills and grow professionally. I am a nice fun and friendly person. I enjoy doing free&open-source side projects and sharing them on GitHub. I do also have a background in the data science field.
user_title: Software Developer
email: hey@cansozbir.com
# twitter_username: lorem_ipsum
github_username:  cansozbir
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
